version: "3"
services:
  jupyter-env:
    container_name: jupyter-env
    image: trading-strategy-jupyter-env:latest
    ports:
      - "127.0.0.1:8989:8989"
    volumes:
      - ./notebooks:/app/notebooks