version: "3"
services:
  cocalc-env:
    container_name: cocalc-env
    image: ghcr.io/tradingstrategy-ai/cocalc-env:${COCALC_ENV_VERSION:-master}
    ports:
      # Map host port 7777 to plain http
      - ${COCALC_ENV_BIND:-7777}:80
    volumes:
      - ./notebooks:/app/notebooks
      - ./.jupyter:/root/.jupyter
      - ./.cache:/root/.cache/tradingstrategy
      - ./.tradingstrategy:/root/.tradingstrategy

