version: "3"
services:
  jupyter_env:
    container_name: jupyter_env
    image: ghcr.io/tradingstrategy-ai/jupyter-env:${JUPYTER_ENV_VERSION:-master}
    ports:
      - ${JUPYTER_ENV_BIND:-8989}:8888
    volumes:
      - ./notebooks:/app/notebooks
      - ./.jupyter:/root/.jupyter
      - ./.cache:/root/.cache/tradingstrategy
      - ./.tradingstrategy:/root/.tradingstrategy
    privileged: true
