version: "3"
services:
  jupyter_env:
    container_name: jupyter_env
    image: ghcr.io/tradingstrategy-ai/jupyter-env:${JUPYTER_ENV_VERSION:-master}
    ports:
      - ${JUPYTER_ENV_PORT:-8989}:8888
    volumes:
      - ./notebooks:/app/notebooks
      - ./jupyter_config.py:/root/.jupyter/jupyter_config.py
      - ./.cache:/root/.cache/tradingstrategy
      - ./.tradingstrategy:/root/.tradingstrategy
    # command: jupyter-lab --config /app/jupyter_config.py
    privileged: true
