version: "3"
services:
  jupyter_env:
    container_name: jupyter_env
    image: ghcr.io/tradingstrategy-ai/jupyter-env:${JUPYTER_ENV_VERSION:-master}
    ports:
      - "127.0.0.1:8989:8989"
    volumes:
      - ./notebooks:/app/notebooks